# Generated by Django 4.2.16 on 2026-02-09 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='quotation_items/'),
        ),
    ]
