# Generated by Django 6.0 on 2025-12-19 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('type', models.CharField(default='info', max_length=50)),
            ],
        ),
    ]
