# Generated by Django 4.2.16 on 2026-02-11 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_quotationitem_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('specification', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'PD_machine',
            },
        ),
        migrations.CreateModel(
            name='PDService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('specification', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'PD_service',
            },
        ),
        migrations.CreateModel(
            name='PDSparepart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('specification', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'PD_sparepart',
            },
        ),
        migrations.CreateModel(
            name='PDSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('specification', models.TextField(blank=True, default='')),
                ('product_total', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'PD_system',
            },
        ),
        migrations.CreateModel(
            name='PDWire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('specification', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'PD_wire',
            },
        ),
        migrations.CreateModel(
            name='PDSystemChildproduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('specification', models.TextField(blank=True, default='')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_products', to='crm.pdsystem')),
            ],
            options={
                'db_table': 'PD_system_childproduct',
            },
        ),
    ]
