# Generated by Django 4.2.27 on 2025-12-19 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_alter_deal_id'),
        ('crm', '0004_userprofile_profile_picture'),
    ]

    operations = [
    ]
