# Generated by Django 4.2.16 on 2026-02-16 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_merge_0003_receipt_0003_pd_tables'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='division',
            new_name='attn_division',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='mobile',
            new_name='attn_mobile',
        ),
        migrations.AddField(
            model_name='customer',
            name='cc',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='customer',
            name='cc_division',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='customer',
            name='cc_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='customer',
            name='cc_mobile',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
