# Generated by Django 4.2.27 on 2025-12-22 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_activityschedule'),
        ('crm', '0005_merge_20251219_1202'),
    ]

    operations = [
    ]
