# Generated by Django 6.0 on 2025-12-19 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_activityschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='last_notification_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
