# Generated by Django 4.2.27 on 2025-12-22 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_deal_last_notification_date'),
        ('crm', '0006_merge_0005_activityschedule_0005_merge_20251219_1202'),
    ]

    operations = [
    ]
