# Generated by Django 4.2.16 on 2026-02-16 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_rename_division_customer_attn_division_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='attn',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='attn_division',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='attn_mobile',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cc',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cc_division',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cc_email',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cc_mobile',
            field=models.TextField(blank=True),
        ),
    ]
