# Generated by Django 4.2.16 on 2026-02-16 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_alter_customer_attn_alter_customer_attn_division_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PMProject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('task_total', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'PM_project',
            },
        ),
        migrations.CreateModel(
            name='PMTask',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('task_start_date', models.DateField(blank=True, null=True)),
                ('task_end_date', models.DateField(blank=True, null=True)),
                ('project', models.ForeignKey(db_column='Project_id', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='crm.pmproject')),
            ],
            options={
                'db_table': 'PM_task',
            },
        ),
    ]
