# Generated by Django 4.2.27 on 2025-12-22 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_remove_deal_last_notification_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='tax_id',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
