# Generated by Django 4.2.27 on 2025-12-22 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_deal_address_deal_tax_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='items',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
