# Generated by Django 4.2.27 on 2025-12-23 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_deal_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('tax_id', models.CharField(blank=True, max_length=50)),
                ('address', models.TextField(blank=True)),
            ],
        ),
    ]
