# Generated by Django 4.2.16 on 2026-02-17 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_add_color_status_to_pmproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='eit',
            name='organization_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='eit',
            name='tax_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
