# Generated by Django 4.2.16 on 2026-02-17 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_add_color_status_to_pmproject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingnote',
            name='bn_paid_amount',
            field=models.DateField(blank=True, null=True, verbose_name='Bn tax paid'),
        ),
    ]
