# Generated by Django 4.2.16 on 2026-02-17 04:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_eit_organization_id_eit_tax_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxInvoice',
            fields=[
                ('tax_invoice_id', models.AutoField(primary_key=True, serialize=False)),
                ('tax_invoice_code', models.CharField(max_length=100, unique=True)),
                ('issued_date', models.DateField(default=django.utils.timezone.localdate)),
                ('customer_branch', models.CharField(blank=True, max_length=255)),
                ('payment_type', models.CharField(blank=True, max_length=255)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tax_invoices', to='crm.customer')),
                ('eit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tax_invoices', to='crm.eit')),
            ],
        ),
    ]
