# Generated by Django 4.2.27 on 2025-12-23 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_customer_created_at_customer_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='customer_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='crm.customer'),
        ),
    ]
