# Generated by Django 4.2.27 on 2025-12-23 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_deal_customer_fk'),
    ]

    def forwards(apps, schema_editor):
        Deal = apps.get_model('crm', 'Deal')
        Customer = apps.get_model('crm', 'Customer')
        for deal in Deal.objects.all():
            name = (deal.customer or "").strip()
            if not name:
                continue
            cust, _ = Customer.objects.get_or_create(
                company_name=name,
                defaults={
                    'tax_id': deal.tax_id or "",
                    'address': deal.address or "",
                }
            )
            deal.customer_fk_id = cust.id
            deal.save(update_fields=['customer_fk'])

    def backwards(apps, schema_editor):
        # No-op: we keep existing char field data intact
        pass

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
