# Generated by Django 4.2.16 on 2026-02-17 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_taxinvoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxinvoice',
            name='items',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
