# Generated by Django 4.2.27 on 2026-02-17 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_cleanup_bn_paid_amount'),
        ('crm', '0014_taxinvoice_items'),
    ]

    operations = [
    ]
