# Generated by Django 4.2.27 on 2025-12-23 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_populate_customer_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='customer',
        ),
        migrations.RenameField(
            model_name='deal',
            old_name='customer_fk',
            new_name='customer',
        ),
    ]
