# Generated by Django 4.2.27 on 2026-02-18 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_merge_20260217_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationitem',
            name='specification',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='billingnote',
            name='bn_paid_amount',
            field=models.DateField(blank=True, null=True, verbose_name='Bn paid date'),
        ),
    ]
