# Generated by Django 4.2.16 on 2026-02-18 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0016_quotationitem_specification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='file_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
