# Generated by Django 4.2.16 on 2026-02-18 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0017_quotation_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='qo_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
