# Generated by Django 4.2.16 on 2026-02-18 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0018_alter_quotation_file_name_alter_quotation_qo_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='cus_respon_attn',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='quotation',
            name='cus_respon_cc',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='quotation',
            name='cus_respon_cc_div',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='quotation',
            name='cus_respon_cc_email',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='quotation',
            name='cus_respon_cc_mobile',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='quotation',
            name='cus_respon_div',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='quotation',
            name='cus_respon_mobile',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='quotation',
            name='customer_address',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='quotation',
            name='customer_email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='quotation',
            name='customer_fax',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='quotation',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='quotation',
            name='customer_tax_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='quotation',
            name='eit_address',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='quotation',
            name='eit_fax',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='quotation',
            name='eit_mobile',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='quotation',
            name='eit_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='quotation',
            name='eit_phone',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
