# Generated by Django 4.2.16 on 2026-02-19 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0017_deal_extra_contacts'),
        ('crm', '0019_quotation_cus_respon_attn_quotation_cus_respon_cc_and_more'),
    ]

    operations = [
    ]
