# Generated by Django 6.0 on 2025-12-23 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_activityschedule_assignee_activityschedule_start_at_and_more'),
        ('crm', '0020_alter_activityschedule_id_alter_contact_id_and_more'),
    ]

    operations = [
    ]
