# Generated by Django 4.2.16 on 2026-02-19 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0020_merge_20260219_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingnote',
            name='bn_branch',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='quotation',
            name='customer_branch',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
