# Generated by Django 4.2.16 on 2026-02-22 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0021_billingnote_bn_branch_quotation_customer_branch'),
        ('crm', '0021_branch'),
    ]

    operations = [
    ]
