# Generated by Django 4.2.27 on 2025-12-23 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0021_deal_stage_fk_alter_activityschedule_id_and_more'),
    ]

    def forwards(apps, schema_editor):
        Deal = apps.get_model('crm', 'Deal')
        Stage = apps.get_model('crm', 'Stage')
        for deal in Deal.objects.all():
            name = (getattr(deal, 'stage', '') or '').strip()
            if not name:
                continue
            stage, _ = Stage.objects.get_or_create(
                stage_name=name,
                defaults={'stage_order': 0}
            )
            deal.stage_fk_id = stage.id
            deal.save(update_fields=['stage_fk'])

    def backwards(apps, schema_editor):
        pass

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
