# Generated by Django 4.2.16 on 2026-02-23 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0022_merge_20260222_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='attn_email',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='branch',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
