# Generated by Django 4.2.27 on 2025-12-23 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0022_populate_stage_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='stage',
        ),
        migrations.RenameField(
            model_name='deal',
            old_name='stage_fk',
            new_name='stage',
        ),
    ]
