# Generated by Django 4.2.16 on 2026-02-23 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0023_customer_attn_email_customer_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='attn_position',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='cc_position',
            field=models.TextField(blank=True),
        ),
    ]
