# Generated by Django 4.2.27 on 2025-12-23 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0023_swap_stage_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='address',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='email',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='expected_close',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='items',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='tax_id',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='title',
        ),
        migrations.AlterField(
            model_name='deal',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='deal',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='crm.customer'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='priority',
            field=models.CharField(max_length=20),
        ),
    ]
