# Generated by Django 4.2.27 on 2025-12-23 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0024_remove_deal_address_remove_deal_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.customer'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='crm.stage'),
        ),
    ]
