# Generated by Django 4.2.16 on 2026-02-23 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0024_customer_attn_position_customer_cc_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cc',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cc_division',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cc_email',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cc_mobile',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cc_position',
            field=models.TextField(blank=True, default=''),
        ),
    ]
