# Generated by Django 4.2.27 on 2025-12-25 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0026_alter_activityschedule_id_alter_contact_id_and_more'),
        ('crm', '0026_lead'),
    ]

    operations = [
    ]
