# Generated by Django 4.2.27 on 2025-12-25 02:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0027_merge_20251225_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='contact',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='deal',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='deal',
            name='currency',
            field=models.CharField(default='฿', max_length=10),
        ),
        migrations.AddField(
            model_name='deal',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='deal',
            name='expected_close',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='items',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='deal',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='deal',
            name='tax_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='deal',
            name='title',
            field=models.CharField(default='Untitled Deal', max_length=200),
        ),
        migrations.AlterField(
            model_name='deal',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='deal',
            name='priority',
            field=models.CharField(default='medium', max_length=20),
        ),
    ]
