# Generated by Django 4.2.27 on 2025-12-25 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0028_deal_address_deal_contact_deal_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='currency',
        ),
    ]
