# Generated by Django 4.2.27 on 2025-12-25 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0029_remove_deal_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='currency',
            field=models.CharField(default='฿', max_length=10),
        ),
    ]
