# Generated by Django 4.2.27 on 2025-12-26 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0030_deal_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='po_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
