# Generated by Django 4.2.27 on 2026-01-01 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0031_deal_po_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='stage',
            field=models.CharField(default='New', max_length=50),
        ),
        migrations.DeleteModel(
            name='Stage',
        ),
    ]
