# Generated by Django 4.2.27 on 2026-01-02 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0033_deal_salesperson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='salesperson',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
