# Generated by Django 4.2.27 on 2026-01-03 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0034_alter_deal_salesperson'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activityschedule',
            old_name='text',
            new_name='activity_name',
        ),
        migrations.RenameField(
            model_name='activityschedule',
            old_name='assignee',
            new_name='salesperson',
        ),
    ]
