# Generated by Django 4.2.27 on 2026-01-03 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0035_rename_text_activityschedule_activity_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityschedule',
            name='customer',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
