# Generated by Django 4.2.27 on 2026-01-04 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0036_activityschedule_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityschedule',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
