# Generated by Django 6.0 on 2026-01-05 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0038_activityschedule_reminders_split'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='contact_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
