# Generated by Django 4.2.27 on 2026-01-05 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0038_activityschedule_reminders_split'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManufacturingOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_order_code', models.CharField(max_length=50)),
                ('product', models.CharField(blank=True, max_length=255)),
                ('product_no', models.CharField(blank=True, max_length=100)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('complete_date', models.DateField(blank=True, null=True)),
                ('production_time', models.CharField(blank=True, max_length=100)),
                ('sales_department', models.CharField(blank=True, max_length=255)),
                ('production_department', models.CharField(blank=True, max_length=255)),
                ('supplier', models.CharField(blank=True, max_length=255)),
                ('supplier_date', models.DateField(blank=True, null=True)),
                ('recipient', models.CharField(blank=True, max_length=255)),
                ('recipient_date', models.DateField(blank=True, null=True)),
                ('component_status', models.CharField(blank=True, max_length=50)),
                ('state', models.CharField(blank=True, max_length=50)),
                ('items', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manufacturing_orders', to='crm.customer')),
                ('po', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manufacturing_orders', to='crm.purchaseorder')),
            ],
        ),
    ]
