# Generated by Django 6.0 on 2026-01-12 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0039_customer_contact_name'),
        ('crm', '0039_manufacturingorder'),
    ]

    operations = [
    ]
