# Generated by Django 4.2.27 on 2026-01-09 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0039_customer_contact_name'),
        ('crm', '0043_transfer_responsibles_drop_departments'),
    ]

    operations = [
    ]
