# Generated by Django 6.0 on 2026-01-12 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0040_merge_20260112_0142'),
        ('crm', '0044_merge_20260109_1402'),
    ]

    operations = [
    ]
