# Generated by Django 4.2.27 on 2026-01-13 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0045_merge_20260112_0421'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('product_version', models.CharField(blank=True, max_length=100)),
                ('type', models.CharField(blank=True, max_length=100)),
                ('product_image', models.TextField(blank=True)),
                ('system', models.CharField(blank=True, max_length=255)),
                ('system_image', models.TextField(blank=True)),
                ('component', models.CharField(blank=True, max_length=255)),
                ('component_image', models.TextField(blank=True)),
                ('component_quantity', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
