# Generated by Django 6.0 on 2026-01-20 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0049_componententry_component_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='contact_name',
        ),
    ]
