# Generated by Django 4.2.16 on 2026-01-21 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0049_componententry_component_table'),
        ('crm', '0050_remove_customer_contact_name'),
    ]

    operations = [
    ]
