# Generated by Django 4.2.16 on 2026-01-21 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0051_merge_20260121_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityschedule',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
