# Generated by Django 6.0 on 2026-01-27 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0054_emailattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='company',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
