# Generated by Django 4.2.16 on 2026-01-26 04:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0054_emailattachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='EIT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=255)),
                ('eit_mobile', models.CharField(blank=True, max_length=50)),
                ('eit_telephone', models.CharField(blank=True, max_length=50)),
                ('eit_fax', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='details',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='items',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='number',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='totals',
        ),
        migrations.AddField(
            model_name='customer',
            name='cus_fax',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='quotation',
            name='created_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='quotation',
            name='cus_respon_attn',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='quotation',
            name='cus_respon_div',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='quotation',
            name='cus_respon_mobile',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='quotation',
            name='delivery',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='quotation',
            name='invoice_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='payment_terms',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='quotation',
            name='qo_code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='remark',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='shipment_location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='quotation',
            name='trade_terms',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='quotation',
            name='validity',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations', to='crm.customer'),
        ),
        migrations.CreateModel(
            name='QuotationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quo_item', models.CharField(blank=True, max_length=255)),
                ('quo_model', models.CharField(blank=True, max_length=255)),
                ('quo_description', models.TextField(blank=True)),
                ('quantity', models.IntegerField(default=1)),
                ('quo_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotation_items', to='crm.quotation')),
            ],
        ),
    ]
