# Generated by Django 4.2.16 on 2026-01-27 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0055_eit_remove_quotation_details_remove_quotation_items_and_more'),
        ('crm', '0055_userprofile_company'),
    ]

    operations = [
    ]
