# Generated by Django 4.2.16 on 2026-01-26 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0055_eit_remove_quotation_details_remove_quotation_items_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='cus_respon_attn',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='cus_respon_div',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='cus_respon_mobile',
        ),
        migrations.AddField(
            model_name='customer',
            name='attn',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='customer',
            name='division',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='customer',
            name='mobile',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
