# Generated by Django 4.2.16 on 2026-01-28 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0056_merge_20260127_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
