# Generated by Django 4.2.16 on 2026-01-26 08:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0056_remove_quotation_cus_respon_attn_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bn_code', models.CharField(max_length=100, unique=True)),
                ('bn_created_date', models.DateField(default=django.utils.timezone.now)),
                ('bn_due_date', models.DateField(blank=True, null=True)),
                ('bn_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('bn_paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('bn_outstanding_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('bn_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('bn_remark', models.TextField(blank=True)),
                ('bn_recipient', models.CharField(blank=True, max_length=255)),
                ('bn_recipient_receive_date', models.DateField(blank=True, null=True)),
                ('bn_payee_date', models.DateField(blank=True, null=True)),
                ('bn_behalf_of', models.CharField(blank=True, max_length=255)),
                ('bn_name_biller', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_notes', to='crm.customer')),
                ('eit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_notes', to='crm.eit')),
            ],
        ),
    ]
