# Generated by Django 4.2.16 on 2026-01-26 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0057_billingnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingnote',
            name='items',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='eit',
            name='address',
            field=models.TextField(blank=True),
        ),
    ]
