# Generated by Django 4.2.16 on 2026-01-28 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0057_task_reminder_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityschedule',
            name='linked_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='crm.task'),
        ),
    ]
