# Generated by Django 4.2.16 on 2026-01-28 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0058_billingnote_items_eit_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='eit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations', to='crm.eit'),
        ),
    ]
