# Generated by Django 4.2.16 on 2026-01-28 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0059_quotation_eit'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='eit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='crm.eit'),
        ),
    ]
