# Generated by Django 4.2.16 on 2026-01-28 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0060_invoice_eit'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='eit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='crm.eit'),
        ),
    ]
