# Generated by Django 4.2.16 on 2026-01-28 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0061_purchaseorder_eit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eit',
            name='address',
            field=models.TextField(blank=True, default='1/120 ซอยรามคําแหง 184 \n แขวงมีนบุรี เขตมีนบุรี \n กรุงเทพมหานคร 10510'),
        ),
        migrations.AlterField(
            model_name='eit',
            name='eit_fax',
            field=models.CharField(blank=True, default='02-052-9544', max_length=50),
        ),
        migrations.AlterField(
            model_name='eit',
            name='eit_mobile',
            field=models.CharField(blank=True, default='000-000-0000', max_length=50),
        ),
        migrations.AlterField(
            model_name='eit',
            name='eit_telephone',
            field=models.CharField(blank=True, default='02-052-9544', max_length=50),
        ),
    ]
