# Generated by Django 4.2.16 on 2026-01-29 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0056_merge_20260127_1038'),
        ('crm', '0062_alter_eit_address_alter_eit_eit_fax_and_more'),
    ]

    operations = [
    ]
