# Generated by Django 4.2.16 on 2026-01-30 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0058_activityschedule_linked_task'),
        ('crm', '0063_merge_20260129_0143'),
    ]

    operations = [
    ]
