# Generated by Django 4.2.16 on 2026-01-30 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0064_merge_20260130_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturingorder',
            name='po_file_content',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manufacturingorder',
            name='po_file_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='manufacturingorder',
            name='po_file_type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
