# Generated by Django 4.2.16 on 2026-02-01 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0065_manufacturingorder_po_file_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerPurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('po_file_name', models.CharField(blank=True, max_length=255)),
                ('po_file_type', models.CharField(blank=True, max_length=100)),
                ('po_file_content', models.BinaryField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_purchase_orders', to='crm.customer')),
            ],
        ),
    ]
