# Generated by Django 6.0 on 2026-02-03 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0066_customerpurchaseorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerpurchaseorder',
            name='description',
        ),
    ]
