# Generated by Django 4.2.16 on 2026-02-03 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0067_remove_customerpurchaseorder_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
