# Generated by Django 4.2.16 on 2026-02-04 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0068_stage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_product_name', models.CharField(max_length=255, unique=True)),
                ('inventory_stock', models.IntegerField(default=0)),
                ('last_updated_day', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
