# Generated by Django 4.2.16 on 2026-02-04 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0069_inventory'),
        ('crm', '0069_permissioncontrol'),
    ]

    operations = [
    ]
