# Generated by Django 4.2.16 on 2026-02-05 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0072_alter_delivery_company_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('duration', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Project Management',
                'verbose_name_plural': 'Project Management',
            },
        ),
        migrations.CreateModel(
            name='SubProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subproject_name', models.CharField(max_length=255, verbose_name='Subproject')),
                ('subproject_duration', models.CharField(max_length=100, verbose_name='Subproject duration')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subprojects', to='crm.projectmanagement')),
            ],
        ),
    ]
