# Generated by Django 4.2.16 on 2026-02-05 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0072_alter_delivery_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='components/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
