# Generated by Django 4.2.16 on 2026-02-05 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0073_component_image_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='systems/'),
        ),
    ]
