# Generated by Django 4.2.16 on 2026-02-05 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0074_system_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='eit',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='eit_headers/'),
        ),
    ]
