# Generated by Django 4.2.16 on 2026-02-05 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0075_eit_header_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
