# Generated by Django 4.2.16 on 2026-02-05 07:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0076_quotation_is_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='created_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
