# Generated by Django 4.2.16 on 2026-02-05 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0077_alter_quotation_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='account_type',
            field=models.CharField(default='normal', max_length=32),
        ),
    ]
