# Generated by Django 4.2.16 on 2026-02-05 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0078_userprofile_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='account_type',
            field=models.CharField(choices=[('normal', 'Normal Account'), ('permission_control', 'Permission Control Account')], default='normal', max_length=32),
        ),
    ]
