# Generated by Django 4.2.16 on 2026-02-06 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0079_alter_userprofile_account_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportticket',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='supportticket',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='supportticket',
            name='customer',
        ),
        migrations.DeleteModel(
            name='Lead',
        ),
        migrations.DeleteModel(
            name='SupportTicket',
        ),
    ]
